### ISSUE TITLE
how to imlement scroll down that triggers scroll sideways

### ISSUE THREAD

**Issue by eddiefangdaqri** [alvarotrigo/pagePiling.js#101]
Hi!

Can pagePilling.js implement something like this http://laurenwickware.com/ where scrolling down will trigger scrolling sideways on the right side of the page? (with possibly different speeds)

Thanks!

Eddie

**Comment by alvarotrigo** [comment]
Define "sideways".

**Comment by eddiefangdaqri** [comment]
scrolling horizontally :)

**Comment by alvarotrigo** [comment]
fullpage.js doesn't provide a way to do it, but you can probably accomplish it using some of the library functions or features.

**Comment by eddiefangdaqri** [comment]
thanks for the reply! :)
