### ISSUE TITLE
noAnchors active state

### ISSUE THREAD

**Issue by fourroses666** [alvarotrigo/pagePiling.js#106]
I would like to hide the anchors, but do need the menu.
So I came to the idea to use a function. (see below)
But then the active state doesn't work anymore.
Is there a better solution to hide the anchors, use the menu and keep the active states?

```
<script>
	function one() {$.fn.pagepiling.moveTo(1);}
	function two() {$.fn.pagepiling.moveTo(2);}
	function three() {$.fn.pagepiling.moveTo(3);}
</script>

<div class="menu">	
	<div class="active"><a href="javascript:void()" onclick="one()">Wie</a></div>
	<div><a href="javascript:void()" onclick="two()">Wie extra</a></div>
	<div><a href="javascript:void()" onclick="three()">Wat</a></div>
</div> 
```

**Comment by alvarotrigo** [comment]
> But then the active state doesn't work anymore.

I don't see why not. Please provide an isolated reproduction in jsfiddle or codepen.

**Comment by fourroses666** [comment]
Made a fiddle but the custom functions are not working there.
One my demo site they are, not sure why..

https://jsfiddle.net/fourroses666/byhn9cza/

**Comment by alvarotrigo** [comment]
https://jsfiddle.net/byhn9cza/1/

**Comment by fourroses666** [comment]
Thanks, had some issues with base href.

But the menu buttons doesn't get an active class when clicked.
This could be fixed by adding some script to the function so I think I will be fine.

**Comment by fourroses666** [comment]
https://jsfiddle.net/fourroses666/byhn9cza/3/ 

It now works when you click on an other button, but when scrolling the class is not added. :(

**Comment by alvarotrigo** [comment]
> The menu buttons still doesn't get an active class when clicked.

Add it yourself just before calling `moveTo`.

**Comment by alvarotrigo** [comment]
> It now works when you click on an other button, but when scrolling the class is not added. :(

Add it yourself using the plugin callbacks such as `onLeave`.

**Comment by fourroses666** [comment]
Do you have an example? its to hard for me to understand.
