### ISSUE TITLE
Possibility to always show navigation tooltip

### ISSUE THREAD

**Issue by fourroses666** [alvarotrigo/pagePiling.js#107]
Hi Alvarotrigo,

When mouse enter it adds the div with tooltip.
Is there a possibility to always show the navigation tooltip?
https://github.com/alvarotrigo/pagePiling.js/blob/master/jquery.pagepiling.js#L894-L907

**Comment by alvarotrigo** [comment]
Not at the moment. 
I'll mark it as an enhancement.

**Comment by fourroses666** [comment]
Thanks, 

Do you know a quick "hardcoded" workaround?
Tried to change the document .on to ready and removed the mouseenter but no success.

**Comment by alvarotrigo** [comment]
Feel free to look into [fullpage.js](https://github.com/alvarotrigo/fullPage.js) for a possible solution.
I implemented in it an option for it: `showActiveTooltip`

**Comment by fourroses666** [comment]
https://github.com/alvarotrigo/pagePiling.js/blob/master/jquery.pagepiling.js#L878

Add:
```nav.find('ul').append('<li data-tooltip="' + tooltip + '"><a href="#' + link + '"><span></span><div class="pp-tooltip ' + options.navigation.position +'">' + tooltip + '</div></a></li>');```

And uncommand 894-907
