### ISSUE TITLE
Sections stack on top of each other when loading

### ISSUE THREAD

**Issue by Madeirense** [alvarotrigo/pagePiling.js#108]
Hi,

First of all great plugin! I am having an issue though and was wondering if there is a way around it. I have a page with 4 sections. Everything works fine but when the page loads all content from all 4 sections seems to stack on top of each other for a second or 2 which looks a bit messy. You can have a look at my demo website here http://paulonatal.com/mnr-website/ when the page loads you'll see all the content from all sections show stacked on top of each other for a few seconds and then everything shows normally.

Would really appreciate if you could give me some advice on how to prevent this from happening.

Thank you very much

**Comment by alvarotrigo** [comment]
Load pagePiling.js in the header of the site.

**Comment by Madeirense** [comment]
Hi, thank you for your quick reply. I am afraid that hasn't really made a difference. The same issue still happens weather pagePiling.js  is loaded on the header or the footer..

**Comment by alvarotrigo** [comment]
Set up an initial size for your sections to height: 100% of the view-port. 
Then you'll only see the 1st one.

**Comment by Madeirense** [comment]
Hi,

Thank you. However that also didn't do the trick.. I ended up fading in the sections after a small delay. Thank you anyway.

**Comment by Saalem420** [comment]
I had same issue. In my case, I forgot to put below peace of code in my js file.
$(document).ready(function() {

  /*
   * Plugin intialization
   */
  $('#pagepiling').pagepiling({
    menu: '#menu',
    anchors: ['page1', 'page2', 'page3', 'page4'],
    sectionsColor: ['white', '#ee005a', '#2C3E50', '#39C'],
    navigation: {
      'position': 'right',
      'tooltips': ['Page 1', 'Page 2', 'Page 3', 'Pgae 4']
    },
    afterRender: function() {
      $('#pp-nav').addClass('custom');
    },
    afterLoad: function(anchorLink, index) {
      if (index > 1) {
        $('#pp-nav').removeClass('custom');
      } else {
        $('#pp-nav').addClass('custom');
      }
    }
  });

});
