### ISSUE TITLE
Googlemap and touch devices 

### ISSUE THREAD

**Issue by fourroses666** [alvarotrigo/pagePiling.js#109]
Stop scrolling (googlemap) and touch devices.
Doesn't work on desktop Firefox, correct, on desktop Chrome it does while it isn't a touch device.
On iphone/touch device Safari it doesn't work.

The script I use:

```
onLeave: function(index, nextIndex, direction){
	if(index == 5 && direction =='down'){
		normalScrollElements: '#kaart'
	}
	else if(index == 7 && direction == 'up'){
		normalScrollElements: '#kaart'
	}
}
```

Any clue?

**Comment by alvarotrigo** [comment]
See [this answer](https://github.com/alvarotrigo/fullPage.js/issues/1281) in fullpage.js. 
Similar issue.
