### ISSUE TITLE
Use no anchores, possible to go to a new page section?

### ISSUE THREAD

**Issue by fourroses666** [alvarotrigo/pagePiling.js#110]
I would like to use a link from page A, click and go to page B on --> section 3.
It works when using anchors.

Is it possible to make it work without the anchors?

**Comment by alvarotrigo** [comment]
Sure, use the [`moveTo`](https://github.com/alvarotrigo/pagePiling.js#movetosection) function.

**Comment by fourroses666** [comment]
But how to "trigger" it from an other page. On page A needs to be a link to section 3 of page B.

**Comment by alvarotrigo** [comment]
Then you need anchors.

**Comment by fourroses666** [comment]
ok thanks. at first it didn't work even with anchors, but after changing "window on.load" it worked again.
