### ISSUE TITLE
Anchor on a scrollable slide without jumping to another pp-section

### ISSUE THREAD

**Issue by nychinn** [alvarotrigo/pagePiling.js#111]
Hi,

Is there a way for me to go to an anchor on a scrollable slide without jumping to another pp section?

I have triggered a link to go to a a div in the same slide, but it always goes back to the first slide. How can I make this go to an anchor the way it would normally?

```
$(document).on('click', '.goToBot', function(e) {
    e.preventDefault();
    window.location.href = '#bottom';
});
```

**Comment by alvarotrigo** [comment]
At the moment you can't use anchors if they do not belong to pagePiling.js I'm afraid.

**Comment by nychinn** [comment]
Thank you.

For now, I have used scrollTop() to scroll to the part of the page when $('#bottom') is.
