### ISSUE TITLE
Horizontal scrolling inside vertical scrolling.

### ISSUE THREAD

**Issue by Madeirense** [alvarotrigo/pagePiling.js#113]
Can I have an horizontal scrolling section with unlimited width inside a vertical scrolling section? If you have a look at this url http://paulonatal.com/mnr-website/ Basicaly I want the animation you see on the first section to spread across a timeline like horizontal scrollable section which would scroll on user action.

**Comment by alvarotrigo** [comment]
> Can I have an horizontal scrolling section with unlimited width inside a vertical scrolling section?

pagePiling.js doesn't provide anything to facilitate it, but that doesn't mean you can not do it yourself somehow.

**Comment by Madeirense** [comment]
Ok,  thank you
