### ISSUE TITLE
Slide up or down both visible sections on change

### ISSUE THREAD

**Issue by Madeirense** [alvarotrigo/pagePiling.js#114]
Hi, if you have a look at the following url http://paulonatal.com/mnr-website/ you'll see I have a few sections where on transition the current section slides up or down and the next section is then displayed. I was wondering if it's possible to have the leaving section and the next section both slide up or down according to the which direction the user is scrolling.

**Comment by alvarotrigo** [comment]
2 sections at a time? Nop, the plugin doesn't provide such option. But I guess you can try to do it by yourself applying the required css transforms to the section you want to move.
You can do this in a callback.
