### ISSUE TITLE
[Suggestion] Why not use simple css :target?

### ISSUE THREAD

**Issue by equinusocio** [alvarotrigo/pagePiling.js#120]
When this plugin use anchors why not use the css way with the `:target` selector to fire transitions/transformations?

**Comment by alvarotrigo** [comment]
Not sure what you mean by that. Can you elaborate it?

**Comment by equinusocio** [comment]
We can use the css `:target` selector to show/hide panels that are in the #target url. The js can provide some settings but it can use the `:target` pseudo-selector when scrolling and tap/touch/swiping, just changing che #anchor url

**Comment by alvarotrigo** [comment]
And what is the advantage of that?

Besides, pagePiling.js can be used without anchors too as can be seen in [this demo](http://alvarotrigo.com/pagePiling/examples/noAnchor.html).

**Comment by equinusocio** [comment]
When the anchors is active, you can let users using their own animations/transformations, even 3D transformations. Without passing through the js configuration

**Comment by alvarotrigo** [comment]
Using javascript gives us total control over the state of the page.
Defining vertical or horizontal sections, the optional use of css3 transformations (css3 option), the optional and independent use of anchors in the URL etc.
It provides much more flexibility. 

I see your point regarding custom CSS animations. But it is a less flexible solution I believe.
