### ISSUE TITLE
Small options issues

### ISSUE THREAD

**Issue by exadeci** [alvarotrigo/pagePiling.js#122]
I was using fullPage.js and decided to switch to pagePiling.js and I noticed some small issues:

- `navigation: true` works for fullPage but not for pagePiling `navigation: {}` works tough
- `normalScrollElements` works for fullPage but with pagePiling it just locks the scrolling,  adding `.pp-scrollable` works great tough.

Aside from that everything that I've tried works perfectly, thanks !

**Comment by alvarotrigo** [comment]
They never tried to be identical :) So nothing weird on having to use `navigation` in a different way.

Regarding `normalScrollElements`, if you think it is not working as expected just provide an isolated reproduction in jsfiffle or codepen.
