### ISSUE TITLE
Is there any limit of the number of sections?

### ISSUE THREAD

**Issue by Liangaas** [alvarotrigo/pagePiling.js#130]
I've found that when the number of sections is larger than 15, the 16th section just doesn't work, neither do the sections that larger than 16th, I can't find any explanation for this phenomenon. Waiting for your help.

**Comment by alvarotrigo** [comment]
No limit.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the issue with no external CSS and JS and with the less minimum code to reproduce it.
