### ISSUE TITLE
Pagepiling not working

### ISSUE THREAD

**Issue by aratibhandare** [alvarotrigo/pagePiling.js#132]
When page is loading sections appear momentarily once loading is complete it does not show any sections but just blank white screem
<img width="1267" alt="screen shot 2017-06-15 at 2 50 20 pm" src="https://user-images.githubusercontent.com/2684167/27174488-f6aeeda8-51d9-11e7-8e13-bc025e677182.png">
Any help will be appreciated, I have deadline to complete this.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
