### ISSUE TITLE
Allow scroll only inside section

### ISSUE THREAD

**Issue by acegilz** [alvarotrigo/pagePiling.js#133]
I would like to allow scrolling inside each section but don't allow transitions via scroll or keyboard.
I am using links with `$.fn.pagepiling.moveTo(3);` 

Is there any way to achieve this?

With `$.fn.pagepiling.setAllowScrolling(false);` I lose completely the scrolling which is not ok for bigger sections

**Comment by alvarotrigo** [comment]
Your solution seem to be ok.

**Comment by acegilz** [comment]
but unfortunately it's not..
This way I cannot scroll at all, even inside the current div

**Comment by alvarotrigo** [comment]
Have you tried using the class `pp-scrollable` detailed in the docs?
Find a tutorial explaning its usage [here](https://onextrapixel.com/how-to-create-a-beautiful-fullscreen-single-scrolling-page-like-huge-inc/).
