### ISSUE TITLE
Navigation manipulation

### ISSUE THREAD

**Issue by peterlunglum** [alvarotrigo/pagePiling.js#135]
I have a large content section where I want the user to be able to scroll using pagepiling. I have been trying to add headroom JS and other ways of manipulating a header, where when the user reaches a scrollable section, the header will disappear unless the user scrolls upwards. Currently, it's not working. Is there a reason why this wouldn't work?

**Comment by alvarotrigo** [comment]
It doesn't seem to be a pagePiling.js issue but a specific one for your use case. 
I'll close the issue as I do not provide support for those kind of questions here, only for issues and bugs directly related with the library.
