### ISSUE TITLE
pagePiling breaks with too many sections

### ISSUE THREAD

**Issue by laurayanguas01** [alvarotrigo/pagePiling.js#136]
Hi! I love pagePiling! But it seems to break when I have more than certain number of sections. It is working fine for 30+ sections, but when I have up to 40, the animations between sections break when going back to the previous slide. You can see what I mean here: http://teckeldesigns.com.ar/naima_testing/lookbook.php. 

Is there anyway I can solve this, or maybe I am doing something wrong?
Thanks for the help!

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Please provide a reproduction with the less minimum HTML code required and no external CSS or JS to pagePiling.js. This way we'll make sure the issue is not in your code and you'll make things easier for me to test.

**Comment by laurayanguas01** [comment]
Hi! Could you help me with the code as is? Name a price if you are
interested! I am not a skilled programmer and surely the mistake is mine,
but I really need this to work as is. It works perfectly up to 30 sections.
Thanks in advance.
Laura

2017-07-31 11:18 GMT-03:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
I'm [on holidays now](https://twitter.com/IMAC2/status/882578027162587136), so I can not provide you this kind of support at the moment I'm afraid. 

But make sure to check your code, your error is probably not within pagePiling.js.
I can see errors in your js console.

**Comment by laurayanguas01** [comment]
Ok, thank you! Enjoy your holidays!

2017-07-31 11:39 GMT-03:00 Álvaro <notifications@github.com>:

**Comment by laurayanguas01** [comment]
Update: the problem is happening only on apple laptops. Any ideas? I've
been reading previous issues with mac trackpads and pagePiling! just
pointing me in the right direction would be of great help! Thanks in
advance and sorry to disturb you!

2017-07-31 11:40 GMT-03:00 Laura Yanguas <laurayanguas01@gmail.com>:
