### ISSUE TITLE
CSS making the page not scroll

### ISSUE THREAD

**Issue by sjm375** [alvarotrigo/pagePiling.js#137]
Hello, 

I am trying to implement this javascript. Here is a codepen where I added my code.

https://codepen.io/sam-sociallyin/pen/YrQvEj

When I add the css files, the page does not scroll down at all, is stuck on the first slider.

**Comment by alvarotrigo** [comment]
You are not including jQuery.

**Comment by alvarotrigo** [comment]
You are neither including the pagePiling.js file in your codepen.

**Comment by sjm375** [comment]
I added the pagepiling.js and I'm still not getting it to work. Sorry for the beginner questions.

**Comment by sjm375** [comment]
When you say I am not including jquery does that mean not linking it? I added a <script> link

**Comment by alvarotrigo** [comment]
I don't see jquery or pagepiling files in the codepen you created.
