### ISSUE TITLE
Overflow: hidden on body tag

### ISSUE THREAD

**Issue by FedericoPandolfi** [alvarotrigo/pagePiling.js#143]
Hi,

first of all thanks for this amazing plugin. I had some issues integrating the npm package in an Angular project as there's a CSS overflow attribute in body tag that prevents the other children from scrolling correctly. Was this intentional or is it a bug? Maybe this approach is a little bit "aggressive" IMHO.

**Comment by alvarotrigo** [comment]
`overflow:hidden` is required to hide the scroll bars.
