### ISSUE TITLE
.htaccess does not allows the folder be readed by apache

### ISSUE THREAD

**Issue by kalilmaciel** [alvarotrigo/pagePiling.js#147]
I downloaded the project using NPM. Every time when I was trying read the file, my project was saying "File not Found" and giving error 500. The problem was solved when I deletet the .htaccess file inside folder pagepiling.js

**Comment by alvarotrigo** [comment]
I don't see any .htaccess file on github?
https://github.com/alvarotrigo/pagePiling.js

Neither after installing it using npm.

**Comment by kalilmaciel** [comment]
Hi, You can not see normally using the explorer because it is a hidden file. When I open the project using any code editor like Sublime, it show to you.

**Comment by kalilmaciel** [comment]
I don't know if the NPM is putting this file when I do "npm install --save pagepiling.js "
I'm usin NPM 7 in Windows 10 64 bits

**Comment by alvarotrigo** [comment]
I noticed the npm version had files that shouldn't be there, but didn't find any .htaccess there, not even from Sublime. 

I created a new version 1.5.5 containing the exact same files as the github repository.

**Comment by kalilmaciel** [comment]
You just released a new version without a lot of junk files that was on previous version. This new version has  not the .htaccess file.

**Comment by kalilmaciel** [comment]
Well, the fact is that now it's working like a charm. Thanks a lot. I'm your project's fan.

**Comment by alvarotrigo** [comment]
:) Glad you got it working!!
