### ISSUE TITLE
When using direction: horizontal first pagepiling section is overlaid meaning you can't click content in subsequent sections

### ISSUE THREAD

**Issue by davidnorwich** [alvarotrigo/pagePiling.js#155]
Using direction: horizontal and have a link on each pagepiling section which is not clickable because the first section is still technically above it. Works fine using direction: vertical.

**Comment by alvarotrigo** [comment]
I can't seem to be able to reproduce it on the [demo page](https://alvarotrigo.com/pagePiling/examples/horizontalScroll.html#page2).

I can select and click links on 2nd and 3rd slides.
