### ISSUE TITLE
Page load error - Quick flash of 2nd Page

### ISSUE THREAD

**Issue by dwsiddall** [alvarotrigo/pagePiling.js#156]
When the page is loaded, there is a quick flash of the content on page 2 (section 2) before displaying Page 1.

I do not have the site online yet, but I can paste it here.  Here is a screengrab of what I see before the main page loads....followed by the main page as it normally looks.

![image2](https://user-images.githubusercontent.com/30631241/43038206-3294bcc2-8ce3-11e8-854b-d3118cefc8db.jpg)
![image3](https://user-images.githubusercontent.com/30631241/43038215-52564b48-8ce3-11e8-95fc-ddd6d7612bce.jpg)

NOTE:  I am running multiple versions of jQuery because I have a slider on Page 1.  I am using jQuery noConflict and it works fine.  I also have mouse scrolling disabled so that if there is content on the page that overflows, the user can scroll down without changing pages.  None of these should casue the "flash".

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>BBQ Restaurant</title>
	<meta name="keywords"  content="BBQ,food,restaurant,cafe,eats,best,hungry,diner" />
	<meta name="Resource-type" content="Document" />

	<link rel="stylesheet" type="text/css" href="css/jquery.pagepiling.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/slider-pro.css"/>    
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" 
    	integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" 
    	crossorigin="anonymous">

   	<script src="js/jquery-1.8.3.js"></script>  
	<script type="text/javascript" src="js/jquery.pagepiling.js"></script>
    <script type="text/javascript" src="js/jquery.sliderPro.js"></script>     

   	<script src="js/jquery-1.11.0.min.js"></script> 
    
    <script type="text/javascript">
		jQuery.noConflict();
        var $1 = jQuery;
	</script>
 
    <script type='text/javascript'>
		$( document ).ready(function( $1 ) {
		$( '#slider_container' ).sliderPro({
                width: 800,
                height: 375,
                orientation: 'vertical',
                loop: true,
				AllowScrolling: false,
                arrows: true,
                buttons: false,
                thumbnailsPosition: 'right',
                thumbnailPointer: true,
                thumbnailWidth: 0,
            });
        });
    </script>
         
	<script type="text/javascript">

		$( document ).ready(function( $1 ) {
			/*
			* Plugin intialization
			*/
	    	$('#pagepiling').pagepiling({
	          	direction: 'horizontal',
	    		menu: '#menu',
	    		anchors: ['page1', 'page2', 'page3', 'page4'],
			    sectionsColor: ['white', '#ee005a', '#2C3E50', '#39C'],
			    navigation: {
			    	'position': 'right',
			   		'tooltips': ['Page 1', 'Page 2', 'Page 3', 'Pgae 4']
			   	},
			    afterRender: function(){
			    	$('#pp-nav').addClass('custom');
			    },
			    afterLoad: function(anchorLink, index){
			    	if(index>1){
			    		$('#pp-nav').removeClass('custom');
			    	}else{
			    		$('#pp-nav').addClass('custom');
			    	} 
			    }
				
				});$.fn.pagepiling.setAllowScrolling(false); /* === TURNS OFF MOUSE SCROLLING === */
		});
    </script>
 
	<script type='text/javascript'>
	jQuery1_11 ( '#slider_container' ).sliderPro({
            width: 970,
            height: 450,
            orientation: 'vertical',
            loop: true,
            arrows: true,
            buttons: false,
            thumbnailsPosition: 'right',
            thumbnailPointer: true,
            thumbnailWidth: 0,
        });

</script>

</head>
<body>
	<ul id="menu">
		<li data-menuanchor="page1" class="active"><a href="#page1">Home</a></li>
		<li data-menuanchor="page2"><a href="#page2">Menu</a></li>
        <li data-menuanchor="page3"><a href="#page3">Staff</a></li>
		<li data-menuanchor="page4"><a href="#page4">Contact</a></li>
	</ul>
	<div id="pagepiling">
	    <div class="section" id="section1">
             
            <div class="home_address">
                <p style="color:white;">5612 MAIN STREET,</p>
                <p style="color:white;">AUBURN, ME 04210</p>
                <p style="padding-top:12px; color:white;"><i class="fa fa-phone fa-xs"></i>&nbsp;&nbsp;207.440.8955</p>
        	</div>																			

                
        <div id="slider_container" class="slider-pro">
            <div class="sp-slides">            
                <div class="sp-slide">
                    <img src="imgs/blank.gif" class="sp-image"
                    data-src="imgs/slide01.jpg"
                    data-retina="">
            		<div class="sp-caption"></div>
        		</div>
        
                <div class="sp-slide">
                    <img class="sp-image" src="images/blank.gif"
                    data-src="imgs/slide02.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        		</div>
        
                <div class="sp-slide">
                    <img class="sp-image" src="blank.gif"
                    data-src="imgs/slide03.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        		</div>
        
                <div class="sp-slide">
                    <img class="sp-image" src="blank.gif"
                    data-src="imgs/slide04.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        		</div>
        
                <div class="sp-slide">
                    <img class="sp-image" src="blank.gif"
                    data-src="imgs/slide05.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        		</div>
        
                <div class="sp-slide">
                    <img class="sp-image" src="blank.gif"
                    data-src="imgs/slide06.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        		</div>
                
                <div class="sp-slide">
                    <img class="sp-image" src="blank.gif"
                    data-src="imgs/slide07.jpg"
                    data-retina=""/>
            		<div class="sp-caption"></div>
        	</div>
        </div>

		   <div id="logo">
				<img src="imgs/logos/logo05a.png" alt="Logo" />				
			</div>
			
       </div>
 
 
<div id="footer">&copy;2018-2019 mainelyEATS</div>

	    </div>
 
	    <div class="section" id="section2">
        	<div class="intro">
            <button class="accordion">Section 1</button>
<div class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>    
</div>

<button class="accordion">Section 2</button>
<div class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>

<button class="accordion">Section 3</button>
<div class="panel">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</div>
			</div>
	    </div>
 
<div id="footer">&copy;2018-2019 mainelyEATS</div>
        
	    <div class="section" id="section3">
	    	<div class="intro">
	    		<h1>STAFF</h1>
	    		<p>Just as you expected!</p>
	    		<div id="colors2"></div>
	    		<div id="colors3"></div>
	    	</div>
	    </div>
 
<div id="footer">&copy;2018-2019 mainelyEATS</div>
        
        <div class="section" id="section4">
	    	<div class="intro">
	    		<h1>CONTACT</h1>
	    		<p>Just as you expected!</p>
	    		<div id="colors2"></div>
	    		<div id="colors3"></div>
	    	</div>
	    </div>
        
	</div>
 
<div id="footer">&copy;2018-2019 mainelyEATS</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
        this.classList.toggle("active2");
        var panel = this.nextElementSibling;
        if (panel.style.display === "block") {
            panel.style.display = "none";
        } else {
            panel.style.display = "block";
        }
    });
}
</script>
</body>
</html>

**Comment by alvarotrigo** [comment]
Use in your css the following, assume your pagepiling element has id="pagepiling":

```css
#pagepiling,
.section,
body,
.fp-tableCell,
html {
    height: 100%
}
.section.pp-table{
    display: table;
    table-layout:fixed;
    width: 100%;
}
```
