### ISSUE TITLE
Example videoBackground.html is broken, the video overflows vertically in lower sections.

### ISSUE THREAD

**Issue by SakhirAtwi** [alvarotrigo/pagePiling.js#158]
@alvarotrigo The example videoBackground.html is a bit buggy, the video in the first section overflows into next sections as in the screenshot bellow,

![screenshot_20180807_160824](https://user-images.githubusercontent.com/42070051/43772800-cf097828-9a5c-11e8-8d6e-03dde11fd39c.png)

One quick fix would be,

`#section1{
     overflow: hidden
}`

inside the style tag of example html, which i have done and created the pull request, you can merge it.

Cheers. Happy Coding.

-SakhirAtwi

**Comment by alvarotrigo** [comment]
Fixed!
