### ISSUE TITLE
Timers and AutoPlay

### ISSUE THREAD

**Issue by bradvin** [alvarotrigo/pagePiling.js#16]
Awesome library - thanks!

I was wondering if you have had anyone asking for an autoplay option? So basically you can get rid of the menu and let it play through the pile of pages automatically. If this is done, then you obviously need another option for autoplayDuration which is the amount of time it stays on each page before navigating to the next.

This can then be used in conjunction with the loop option to setup a fullpage slideshow of sorts that can be displayed on a monitor. 

Further to this, you could setup different durations per page/section, so that you could have a video clip on a page that plays for 30 seconds and then moves onto the next page, while other pages only show for 10 seconds as they might only have static images.

Something like this:

```
$('#pagepiling').pagePiling({
    loopBottom: true,
    autoPlay: true,
    autoPlayDuration: [10000, 20000, 5000, 10000]
});
```

**Comment by AntonHonchar** [comment]
It doesn't work well and crashes after a little time.
In Live Demo it's also broken. Any ideas?

**Comment by alvarotrigo** [comment]
Live demo is working for me. You'll have to be a bit more specific and detail under what circumstances it breaks or what you really when by "it crashes".

**Comment by AntonHonchar** [comment]
Thanks for your quick reply. It works for the first. But when you click for navigation dots few times, the slides begin loop with very hight speed and sometimes break order. 
Can you just try on demo? After 1 minute you'll see)
Anyway, the plugin is great,  thank you.

**Comment by alvarotrigo** [comment]
Yeah I see. I forgot to clear the timeout. See this demo:
http://jsfiddle.net/fzwp74kq/1/

Code:
```js
var interval;
var timeout;
var autoPlayDuration = 1000;

$('#pagePiling').pagepiling({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    loopBottom: true,
    afterLoad: function (anchorLink, index) {
        clearInterval(interval);
        clearTimeout(timeout);
        timeout = setTimeout(function () {
            interval = getInterval();
        },autoPlayDuration);
    },
    afterRender: function () {
        interval = getInterval();
    }
});


function getInterval() {
    return setInterval(function () {
        $.fn.pagepiling.moveSectionDown();
    }, autoPlayDuration);
}
```

**Comment by AntonHonchar** [comment]
It'a AMAZING! Work perfect)
You are the best!
Thank you very much!

**Comment by AntonHonchar** [comment]
Hello, alvarotrigo.
I've just found one more interesting thing.
So we have - var autoPlayDuration = 1000;
But first slide (when page load ) change much faster than 1000. After that everything is ok.
Do you have any ideas how to fix that? Because it's really to fast (just first slide)
