### ISSUE TITLE
css position: fixed property object gets stuck in scrollable section

### ISSUE THREAD

**Issue by luxem35** [alvarotrigo/pagePiling.js#162]
CSS Properties
```
* {
    box-sizing: border-box;
}

html, body {
    padding: 0;
    margin: 0;
    font-family: 'Open Sans', sans-serif;
    font-size: 15px;
    line-height: 1.5;
    background-color: #FFFFFF;
    display: block;
    height: 1721px;
    position: relative;
  }

header {
    width: 100%;
    position: fixed;
    top: 0;
    left: 0;
    padding: 0.5% 5% 0 5%;
    box-shadow: 0 3px 10px 0 rgba(0,0,0,0.50);
    background-color: rgba(255,255,255,0.25);
    border: 0 solid #979797;
}
```
pagePiling init
```
$(document).ready(function() {
            $('#pagepiling').pagepiling({
                verticalCentered: false
            });
 });
```

<img width="1440" alt="screen shot 2018-08-09 at 08 54 36" src="https://user-images.githubusercontent.com/23283227/43880647-f86068a2-9bb1-11e8-8087-0adbeabb948e.png">

Nothin wrong when we first came to the pp-scrollable section, footer and header is fixed at their position.

<img width="1440" alt="screen shot 2018-08-09 at 08 54 47" src="https://user-images.githubusercontent.com/23283227/43880674-103ab3a6-9bb2-11e8-8e72-64f18c853dee.png">

After we go to another section and come back to pp-scrollable section, css position: fixed elements gets stuck at their first positions.

**Comment by luxem35** [comment]
By making `position: absolute` and setting the height of the page to 100%, I can achieve the same result as `position:fixed` should in a normal situation.

**Comment by alvarotrigo** [comment]
Fixed positioned elements won't work well within translated3d properties, such as the ones used by pagePiling.js.

Place all your fixed elements outside the pagePiling.js wrapper.

**Comment by luxem35** [comment]
Alright, Thank you :)
