### ISSUE TITLE
Problem using the horizontal navigation plugin in Firefox

### ISSUE THREAD

**Issue by aporreado** [alvarotrigo/pagePiling.js#167]
I'm having trouble using the plugin in firefox browser. When the user scrolls horizontally, the browser blinks between sections. I noticed that it is only in firefox that this happens.

I tested it with the same thing and the same thing happens.

I used a project that is late and now I do not know what to do.

[Example](https://www.lucasgranvilla.com.br/firefox_problem.mp4)

**Comment by aporreado** [comment]
I understand what you meant and I actually read your article, but I do not have many specifications about the error. What I know of him is what is in the video and what I explained.

Only thing I did not put was the Firefox version: Firefox Quantum 62.0.2 (64-bit).

When it rolls between sessions it flashes. Just look at the video and test on your firefox what you will see.

**Comment by alvarotrigo** [comment]
What horizontal plug-in are you talking about? The scroll horizontally extension?

**Comment by aporreado** [comment]
Follow or link: https://alvarotrigo.com/pagePiling/examples/horizontalScroll.html#page1

This is also giving firefox error.

**Comment by alvarotrigo** [comment]
It looks totally fine for me in Firefox.

**Comment by aporreado** [comment]
Watch this 10 sec video: https://www.agenciapunto.com.br/error.mp4

**Comment by alvarotrigo** [comment]
Can't really solve it if I can not reproduce it myself I'm afraid.

**Comment by aporreado** [comment]
What version of your firefox?

**Comment by alvarotrigo** [comment]
Right! I've updated to the latest and now I'm able to reproduce the issue. 
I'll take a look at it eventually!

**Comment by aporreado** [comment]
Ok, if you can really take a look at this, because I have the project ready but I will not be able to deliver it to the client with this bug. It was he who showed me = S

**Comment by alvarotrigo** [comment]
Not planning to take a look at it short term. If you really need a quick fix you can consider contracting my consulting & support services. Please [contact me](https://alvarotrigo.com/#contact) for more info.

**Comment by Haspriahadena** [comment]
Hi @aporreado you can try to overwrite this class >> .pp-section.pp-table with display block (picture - https://imgur.com/a/wVW5ZvE). but you also need to restyling the child wrapper of pp-tableCell like this >> https://imgur.com/a/SU6RPat 

hope it helps

**Comment by aporreado** [comment]
Solved my problem a lot! Grateful!

Please update the plugin!

**Comment by alvarotrigo** [comment]
> you can try to overwrite this class >> .pp-section.pp-table with display block

That will remove the the feature completely the use of the option `verticalCentered`. Therefore, @aporreado, it is not a solid solution to the Firefox rendering issue.
Perhaps you guys can considering opening an issue on the Firefox issues tracker, as it is clearly a Firefox bug.

**Comment by alvarotrigo** [comment]
This has been solved in the latest release 1.5.6
