### ISSUE TITLE
Firefox 63 flicker

### ISSUE THREAD

**Issue by elemdeso** [alvarotrigo/pagePiling.js#168]
Every slide transition flickers on Firefox 63 (Win7 and OSX High Sierra/El Capitan). Other main browsers seems to be fine. The effect is visible on the main page piling demo site.

update: just realised this sounds similar to #167.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by casph** [comment]
Vote up, actually with firefox 64 pagePiling continues this bug.

**Comment by alvarotrigo** [comment]
@casph  and thus the issue still open :)

**Comment by NahshalElN** [comment]
-webkit-tap-highlight-color: rgba(0,0,0,0); Should fix the flickering.

**Comment by NahshalElN** [comment]
> Every slide transition flickers on Firefox 63 (Win7 and OSX High Sierra/El Capitan). Other main browsers seems to be fine. The effect is visible on the main page piling demo site.
> 
> update: just realised this sounds similar to #167.

-webkit-tap-highlight-color: rgba(0,0,0,0); Should fix the flickering on firefox.

**Comment by elemdeso** [comment]
Thanks for the suggestion but it doesn't work for me. Can you explain why (Safari) -prefix would impact Firefox on desktop?

**Comment by NahshalElN** [comment]
> Thanks for the suggestion but it doesn't work for me. Can you explain why (Safari) -prefix would impact Firefox on desktop?

Ah I actually pasted the wrong line, really sorry about that.

this is the line I meant: backface-visibility: hidden;

**Comment by elemdeso** [comment]
It bloody works (when applied to each section) ! I never even heard of backface-visibility. I'll keep an eye on it - but for now looks great. Thank you. Alvaro, up to you to close when you're happy too.

**Comment by NahshalElN** [comment]
> @NahshalElN would you like to provide a Pull Request so I can merge the change?

Yep, done

**Comment by alvarotrigo** [comment]
Fixed thanks to @NahshalElN !!
