### ISSUE TITLE
Urgent!! Issue with larger Page Content

### ISSUE THREAD

**Issue by truelogicapp** [alvarotrigo/pagePiling.js#174]
Hi,

The script is not working fine to me with Larger content. I used pp-scrollable class as well on section but its still not working on Mobile Browser.

http://13.127.98.246/ kindly go this link and open on Mobile Browser. The Slide 3 or 4 screen have larger content but not able to scroll. Its move to next screen. 

Please help.

Thanks & Regards
Raman

**Comment by alvarotrigo** [comment]
I would encourage you to use [fullPage.js](https://alvarotrigo.com/fullPage/) instead.
You can mimic the pagePiling.js behaviour by using the [parallax extension](https://alvarotrigo.com/fullPage/extensions/parallax.html) with offset 100% as you can see in [this article](https://alvarotrigo.com/blog/how-create-tumblr-website-effect/).
