### ISSUE TITLE
Transition Page

### ISSUE THREAD

**Issue by front-bittencourt** [alvarotrigo/pagePiling.js#175]
Hello, first of all I wanted to thank you for this fantastic work.

I wonder if it is possible to get an equal transition effect from fullPage.js where the next element comes in order to keep track of the movement of the element coming out of the screen, as if pushing the current element out.

**Comment by alvarotrigo** [comment]
Why wouldn't you just use fullPage.js instead?

**Comment by front-bittencourt** [comment]
I need a horizontal transition and I saw that there you charge for the horizontal plugin, as at first I do not have the value to supply with this need and help you in the investment, I thought you could adapt this.

I also checked some lib callbacks that would help me.

**Comment by alvarotrigo** [comment]
Unfortunately pagePiling.js works in a completely different way.
I can only suggest you to use fullPage.js. But if you can't afford it you should probably look for another solution somewhere else.

**Comment by front-bittencourt** [comment]
Alright no problem. And again, great work!
