### ISSUE TITLE
height of images seems empty when lazyLoading: true and scrollOverflow: true

### ISSUE THREAD

**Issue by akikokubo** [alvarotrigo/pagePiling.js#176]
Hello, thanks for developing this plugin.
I changed `src` attribute to `data-src` to use lazy loading, and it works all right except on a `scrollOverflow: true` section.

It seems the lazy loading function can't get the height of images on a `scrollOverflow: true` section. Is there any way to solve this?

Advice is much appreciated!

**Comment by alvarotrigo** [comment]
This belongs to fullPage.js. Not to pagePiling,.js repo.

**Comment by akikokubo** [comment]
I'm sorry. Thank you for your reply.
