### ISSUE TITLE
Is't possible to have a smooth scroll?

### ISSUE THREAD

**Issue by biapar** [alvarotrigo/pagePiling.js#177]
Is't possible to have a smooth scroll?

**Comment by alvarotrigo** [comment]
What do you mean?
This is an auto scrolling library :)

**Comment by biapar** [comment]
Yes I know, but I mean that it's possible to made a more smooth scroll that is a if you see this our draft website http://draft.barlotti.it/ I wish to pass the next section with a smooth scroll and not like a jump. To give to the user the impression to scroll a continuos page.

**Comment by alvarotrigo** [comment]
Unfortunately it is not possible with pagePiling.js

I would however recommend you to try [fullpage.js](https://alvarotrigo.com/fullPage/) using the [extension parallax](https://alvarotrigo.com/fullPage/extensions/parallax.html) with `offset:100%` and `autoScrolling:false`.

You can test it yourself in that same demo page.
