### ISSUE TITLE
Can PagePilling section be half page?

### ISSUE THREAD

**Issue by anetk** [alvarotrigo/pagePiling.js#179]
Can we have half slide for one of the sections? Similarly to fullpage.js fitToSection:false?

**Comment by alvarotrigo** [comment]
Unfortunately not. 
However, I would recommend you to check my other JS library: [fullpage.js](https://alvarotrigo.com/fullPage/) that allows you to use smaller sections than the viewport by using the class `fp-auto-height`.

See an example here:
https://codepen.io/alvarotrigo/pen/qOWoZd
