### ISSUE TITLE
Some section is empty

### ISSUE THREAD

**Issue by bquangDinh** [alvarotrigo/pagePiling.js#182]
`<div class="section" id="section1">Section 1</div>`
`<div class="section" id="section2">Section 2</div>`
`<div class="section" id="section3">Section 3</div>`
And when I click the second nav link, it's not show everything, but I click the last one nav link. It show the section 2.

And I relized in my CSS file, I set position: relative (for my purpose) in section class, and something gone wrong. 
Just remove it. I post here so I hope it can help someone.

**Comment by ulumills** [comment]
Ahhh this is exactly what I needed to know. thank you!
