### ISSUE TITLE
PagePilling Slide Menu 

### ISSUE THREAD

**Issue by krenqt** [alvarotrigo/pagePiling.js#199]
Hello,

How can I rename the menu points?
When I point the menu with mouse it says to me "Section 1" , "Section 2"... etc

Where can I rename this points?

Thanks for your answer!

**Comment by alvarotrigo** [comment]
See the `navigation.tooltips`option.

```js
 navigation: {
            'textColor': '#000',
            'bulletsColor': '#000',
            'position': 'right',
            'tooltips': ['section1', 'section2', 'section3', 'section4']
        },
```

**Comment by krenqt** [comment]
Hello,

It's me again.
I tried the navigation.tooltips option but it doesn't work for me.

This is the code in the "jquery.pagepiling.js" file. 
navigation: {
	textColor: '#000',
	bulletsColor: '#000',
	position: 'right',
	tooltips: ['Homepage', 'Videos', 'About us', 'About me', 'About him', 'About theirs']
},

Do I need change anything in the code to rename the menu?

Thank you in advance for your answers.

**Comment by alvarotrigo** [comment]
Nah, you shouldn't be modifying the jquery.pagepiling.js file.
Read in the docs how to initialise the library and how to pass options to it.
Leave the file as it was before.
