### ISSUE TITLE
Sections overlapping

### ISSUE THREAD

**Issue by gmleon** [alvarotrigo/pagePiling.js#201]
Hi!
I would like to use the plugin for a project but even with the simplest version of the demo page, all sections overlap. Here's my test code based on the demoExample, just with a few less elements:

`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="css/jquery.pagepiling.css" />
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script type="text/javascript" src="js/jquery.pagepiling.min.js"></script>
</head>
<body>

  <ul id="menu">
    <li data-menuanchor="page1" class="active"><a href="#page1">Page 1</a></li>
    <li data-menuanchor="page2"><a href="#page2">Page 2</a></li>
    <li data-menuanchor="page3"><a href="#page3">Page 3</a></li>
    <li data-menuanchor="page4"><a href="#page4">Page 4</a></li>
  </ul>

  <div id="pagepiling">
      <div class="section" id="section1">
        <h1>pagePiling.js</h1>
      <p>Create an original scrolling site</p>
      <br />

      </div>
      <div class="section" id="section2">
          <div id="colors"></div>
          <h1>jQuery plugin</h1>
          <p>Pile your sections one over another and access them scrolling or by URL!</p>
      </div>
      <div class="section" id="section3">
        <div class="intro">
          <h1>Configurable</h1>
          <p>Plenty of options, methods and callbacks to use.</p>
          <div id="colors2"></div>
          <div id="colors3"></div>
        </div>
      </div>
      <div class="section" id="section4">
          <h1>Compatible</h1>
          <p>Designed to work on tablet and mobile devices.</p>
          <p>Oh! And its compatible with old browsers such as IE 8 or Opera 12!</p>
      </div>
  </div>
</body>

<script type="text/javascript">
// Initialize pagepiling plugin
$(document).ready(function() {
  $('#pagepiling').pagepiling({
    verticalCentered: false
  });
});
</script>

</html>`

Here's the output:
![image](https://user-images.githubusercontent.com/11980594/80362658-4a7caf00-8883-11ea-8255-6beecfeab70a.png)

This happens both on Google Chrome and Firefox, on Windows 10.
Any ideas? Thank you!!

**Comment by alvarotrigo** [comment]
Sounds like you forgot to add the CSS or you are overwriting the properties on it. 
Try [some of the provided examples](https://github.com/alvarotrigo/pagePiling.js/tree/master/examples) and take it as the starting point to avoid mistakes on the way.
