### ISSUE TITLE
Elementor: The last inner section, present in the DOM, isn't shown

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [alvarotrigo/pagePiling.js#204]
Hi,

I noticed that when using Elementor fullPage.JS with the extension Scroll Horizontally, it was not possible to define a section with the options "Section Behaviour : Full Height" and  "Full Height Columns" activated, with inner sections for which the "Full Height Columns" is not activated. So a résumé would be:

Section (Section Behaviour : Full Height + Full Height Columns) 
-> Column
   ->-> Inner section 1 not full Height (idem its Columns)
   ->-> Inner section 2 not full Height (idem its Columns)

Indeed, the following problem occures: the inner section 1 is full height, the inner section 2 is not displayed (but present in the DOM).

The expected results would be that the Inner sections 1 AND 2 are displayed. They would share at 50%-50% the height of the parent section's column (which is full-screen-height). We could adjust these percents.

Do you know if there is a way to do it by using your plug-in or another extension?

Thank you in advance,
Best regards :-)

**Comment by alvarotrigo** [comment]
For the [official plugin for Elementor fo fullPage.js(https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/#contact) in the page and select the topic "Elementor WordPress plugin for fullPage.js"
