### ISSUE TITLE
Elementor: Official Sticky Header not working when FullPageJS activated

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [alvarotrigo/pagePiling.js#205]
Hi,

I've exactly followed the official setup of a sticky header in Elementor: https://docs.elementor.com/article/459-how-to-create-a-sticky-header . Before activating the FullPageJS extension, the sticky header was correctly shown as I scrolled to the bottom.
However, after this activation, the header doesn't become sticky.

Thank you in advance,
Best regards,

**Comment by alvarotrigo** [comment]
Friendly reminder, you are posting a fullPage.js issue in a pagePiling.js project. Those are completely different projects, so this is definitely not the place to ask those questions :)

And, as I said on [my previous answer](https://github.com/alvarotrigo/pagePiling.js/issues/204):

For the [official plugin for Elementor fo fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/#contact) in the page and select the topic "Elementor WordPress plugin for fullPage.js"
