### ISSUE TITLE
Anchored link not redirect to selected page   

### ISSUE THREAD

**Issue by mohamedellithy** [alvarotrigo/pagePiling.js#208]
my js 
 /*-------------------------
           Page Pilling
    -------------------------*/
    function pagePilling(){

        "use strict";
        
        var ids = [];
        var tooltips = [];
        var colors = [];
        $('.section').each(function () {
            ids.push(this.id+'-page');
            tooltips.push($(this).data("navigation-tooltip"));
            colors.push($(this).data("navigation-color"));
        });
        $('#pagepiling').pagepiling({
            sectionsColor: colors,
            anchors: ids,
            menu: '#myMenu',
            direction: 'vertical',
            verticalCentered: true,
            navigation: {
                'position': 'right',
                'tooltips': tooltips
            },
            loopBottom: true,
            loopTop: true,
            scrollingSpeed: 700,
            easing: 'swing',
            css3: true,
            normalScrollElements: null,
            normalScrollElementTouchThreshold: 5,
            touchSensitivity: 5,
            keyboardScrolling: true,
            sectionSelector: '.section',
            animateAnchor: true,
            //events
            /*afterRender: function() {},
            afterLoad: function(anchorLink, index) {}*/
            afterRender: function(){
                    $('#pp-nav').addClass('custom');
                },
            afterLoad: function(anchorLink, index){
                if(index>1){
                    $('#pp-nav').removeClass('custom');
                }else{
                    $('#pp-nav').addClass('custom');
                }
            }
        });
    }

**Comment by mohamedellithy** [comment]
and anchor not redirect to my select page

**Comment by alvarotrigo** [comment]
Read [the docs](https://github.com/alvarotrigo/pagePiling.js#accesing-sections) where it says:

> **Be careful!** `data-anchor` tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by mohamedellithy** [comment]
my anchor name is "services-page" or anything  "*-page"
and it is unique 
problem not solved !
