### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by VladMokrousov** [alvarotrigo/pagePiling.js#210]
Hi :)
When i'm on the site https://alvarotrigo.com/pagePiling/ and trying to see any example in Examples, get a 404 error. 
Sorry for my English)

**Comment by alvarotrigo** [comment]
Uh! Not good!

I've fixed it! Thanks for reporting it! 👍

**Comment by VladMokrousov** [comment]
Real speedy)
Thank you for the cool plugins!
