### ISSUE TITLE
Pages wont change sometimes on the phone 

### ISSUE THREAD

**Issue by aoljaca** [alvarotrigo/pagePiling.js#213]
If you go here https://www.andrejoljaca.com/#about on your phone, sometimes the scrolling doesn't work and you have to use the hamburger icon to switch between pages, how do I fix this? 

I tried 
normalScrollElementTouchThreshold: 1,
touchSensitivity: 10,

but it did not work.

It works when I scroll in the responsive mode set to iPhone in the chrome browser and works when I refresh the page and then scroll on the phone. 

Thanks

**Comment by aoljaca** [comment]
I think I figured it out. It was a bug with the

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to pagePiling.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by aoljaca** [comment]
Like this: https://codepen.io/aoljaca/pen/RwGZRVM

I haven't done this before so I am not 100% sure if I did what you said right

**Comment by aoljaca** [comment]
I cant seem to find a solution. Any ideas?

**Comment by aoljaca** [comment]
How does pagepiling sense when you are on top of the page and scrolling up or down? Maybe this way I could edit it

**Comment by alvarotrigo** [comment]
> Like this: https://codepen.io/aoljaca/pen/RwGZRVM

Not really. You have to make sure your pagePiling.js effect works on codepen too. 
Import the css/js files and make sure it works there.

**Comment by aoljaca** [comment]
I got it to work by changing it so when you are at top of the page overflow y is set to none and this way the user cant scroll down and it works fine. Then I turn it back to overflow y scroll after one second to make sure the user can still scroll back down if needed. The issue was with the bounce/rubber-band effect on the iPhone. If anyone needs the code let me know.

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! :)
