### ISSUE TITLE
Sections overlapping

### ISSUE THREAD

**Issue by EddiesTech** [alvarotrigo/pagePiling.js#218]
I am experiencing the same issue as here: https://stackoverflow.com/questions/61436573/sections-overlapping-when-using-pagepiling-js
I am using CDNs to get jquery and the CSS and js for pagepiling
I have used the same structure and code in the documentation, yet the two sections overlap. Any way I can fix this?
Here is the URL of where I am trying to do this: https://ssq.eddiestech.co.uk/new2

Hope you can help me, cause this plugin is so cool :)

**Comment by alvarotrigo** [comment]
Have yoo checked the examples folder?
Give it a look and play "find the differences" :) 

https://github.com/alvarotrigo/pagePiling.js/tree/master/examples

If you still struggle then please provide an isolated reproduction in jsfiddle or codepen with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by EddiesTech** [comment]
Interesting blog post, I should link that to people I help, I should really know better :)
Here's a jsfiddle, (I couldn't have made it simpler) and I get the same issue: https://jsfiddle.net/e6tLugd2/1/
Any ideas?

**Comment by alvarotrigo** [comment]
Yeap, that's normal :)

Just add some background to each section. For example:

```css
.section{
    background: white;
}
```

**Comment by alvarotrigo** [comment]
You can also use the property `sectionsColor` if you prefer.
