### ISSUE TITLE
Overlays page navigation

### ISSUE THREAD

**Issue by ectu** [alvarotrigo/pagePiling.js#219]
Hi

As soon as PP is active, it moves to the foreground and overlaps the main navigation, which means it no longer works.
How can this be avoided?

Many thanks

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction of your issue?
I would encourage you to see the examples available too:
https://github.com/alvarotrigo/pagePiling.js/tree/master/examples

**Comment by ectu** [comment]
Navigation z-index = 100
Inner Content z-index = -1

I guess it should be possible to use PP with my standard navigation?

Wordpress page, created with Oxygenbuilder.
The problem exists in all common browsers.

https://user-images.githubusercontent.com/78073705/107021360-539c9400-67a4-11eb-9993-9c92d45dc1d3.mp4

**Comment by alvarotrigo** [comment]
Just use a higher z-index for your navigation? :)

I assume you are placing it outside the pagepiling wrapper? Because if not, you should too.

**Comment by ectu** [comment]
Okay, problem solved.
I now put the z-index in the child element instead of the parent element.

Thanks a lot for your support.

**Comment by alvarotrigo** [comment]
No problem! 👍
