### ISSUE TITLE
Append Navigation Location

### ISSUE THREAD

**Issue by tractanz** [alvarotrigo/pagePiling.js#220]
Hi there,

My site has an html structure of:
```
<html>
	<body>
		<main></main>
	</body>
</html>
```

The content of my site sits within the `<main>` tag and by default the pp navigation gets inserted before the `</body>`.

```
<html>
	<body>
		<main></main>
		**"-- pp-nav inserted here --"**
	</body>
</html>
```

This means the navigation will sit above all elements within `<main>` tag. 

Is it possible to append the navigation to a custom element?

Cheers!

**Comment by alvarotrigo** [comment]
> Is it possible to append the navigation to a custom element?

Not provided out of the box by pagepiling.js but you can use the `afterRender` callback to select it and append i wherever you want by using Javascript :)
