### ISSUE TITLE
Page Speed Issue GTMatrix

### ISSUE THREAD

**Issue by Officialhackercommunity** [alvarotrigo/pagePiling.js#224]
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.

use passive listeners to improve scrolling performance 

How to fix this audit?
To fix this audit, add a passive: true flag to every event listener flagged by GTmetrix. For example,

document.addEventListener('touchstart', onTouchStart, {passive: true});

**Comment by alvarotrigo** [comment]
> How to fix this audit?

There's actually no need for a fix.
This is just an advise, not an error "Consider...."

Read more about it here:
https://github.com/alvarotrigo/fullPage.js/issues/4036#issuecomment-692349929
