### ISSUE TITLE
Android glitch

### ISSUE THREAD

**Issue by annatria** [alvarotrigo/pagePiling.js#225]
Hello Alvaro,
I encountered a problem while using your plugin. I noticed that when I use more than 26 slides the first slides don't scroll nice on android browsers. If I remove the extra slides everything is back to normal. I noticed that glitch on most common android browsers but mozilla firefox, who is the only one working as expected. 
Does it have any limitations on the number of slides or does anyone else has noticed the same issue?

**Comment by alvarotrigo** [comment]
> Does it have any limitations on the number of slides or does anyone else has noticed the same issue?

No, but the more slides you add the slower it will work. 
That's because of the way pagePilign.js is designed.

I would encourage you to move to [fullPage.js](http://alvarotrigo.com/fullPage/) instead. It's a much more mature library and it's being fully maintained unlike pagePiling.js.
