### ISSUE TITLE
Change the effect to horizontal.

### ISSUE THREAD

**Issue by artesfox** [alvarotrigo/pagePiling.js#229]
First of all thank you for the excellent work, I love this effect. I wanted to ask you if there is a way that when I go to a slide it changes the effect to horizontal. I was thinking something like this:

onLeave: function (index, nextIndex, direction) {
 
        if(nextIndex == 3 && direction =='down'){
			direction: 'horizontal',
			          
	          	
			}

I also ask you for an excuse for the code, I'm not a programmer. Thanks

**Comment by alvarotrigo** [comment]
Unfortunately, pagePiling won't support such a thing and it's not a change I'm planning on implementing.
However, I would strongly recommend you to switch to my other component, [fullpage.js](https://alvarotrigo.com/fullPage/).

It can do exactly what you need when combined with the Scroll Horizontally extension ([check example](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html)).

If you need a similar effect to pagePiling you can consider using the [parallax extension](https://alvarotrigo.com/fullPage/extensions/parallax.html) too with an offset of 100%.

It's a much more mature component and keeps up to date. 
Available also for Vue, React, Angular and jQuery wrappers as well as for WordPress with plugins for Gutenberg and Elementor builders.

**Comment by controllz** [comment]
I really love this. Can we maybe program stuff later? Sent from Samsung Galaxy smartphone.
-------- Original message --------From: Álvaro ***@***.***> Date: 3/27/22  6:55 AM  (GMT-05:00) To: "alvarotrigo/pagePiling.js" ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [alvarotrigo/pagePiling.js] Change the effect to horizontal. (Issue #229) 
Unfortunately, pagePiling won't support such a thing and it's not a change I'm planning on implementing.
However, I would strongly recommend you to switch to my other component, fullpage.js.
It can do exactly what you need when combined with the Scroll Horizontally extension (check example).
If you need a similar effect to pagePiling you can consider using the parallax extension too with an offset of 100%.
It's a much more mature component and keeps up to date.
Available also for Vue, React, Angular and jQuery wrappers as well as for WordPress with plugins for Gutenberg and Elementor builders.

**Comment by alvarotrigo** [comment]
> Can we maybe program stuff later? 

What do you mean?
