### ISSUE TITLE
Issue setting direction after initializing

### ISSUE THREAD

**Issue by Nigel2392** [alvarotrigo/pagePiling.js#233]
I'm trying to change the direction every time the page isn't an even number, however this causes some bugs with the pages.
The following code should reproduce, place it in one of the callbacks like `afterLoad`
```
        if (index % 2 == 0) {
            $("#pagepiling").pagepiling().direction="vertical"
        } else {
            $("#pagepiling").pagepiling().direction="horizontal"
        }
```

In short, it works for like 3 pages, then the pages duplicate, and following that it completely bugs out, and horizontal scroll stops working.

**Comment by alvarotrigo** [comment]
Unfortunately, the direction can't be set after initialization.

You can only do it this way:

```js
 if (index % 2 == 0) {
    $('#pagepiling').pagepiling({ 
       direction: ' vertical'
    });
}
else {
    $('#pagepiling').pagepiling({ 
       direction: ' horizontal'
    });
}
```

**Comment by alvarotrigo** [comment]
For a more robust solution, I'd recommend you to check out [fullPage.js](http://alvarotrigo.com/fullPage/), which is actively maintained and has plenty of more features.
