### ISSUE TITLE
Wow js and animate css not working in one go.

### ISSUE THREAD

**Issue by mbyrktr** [alvarotrigo/pagePiling.js#236]
```
onLeave: function(index, nextIndex, direction){
    new WOW().init();
},
```
I want animate.css animations to run with wow.js every time a slide is opened. But when I come back to the working slide, the animation repeats.

**Comment by alvarotrigo** [comment]
Yeap, you need to add some conditions to prevent that.
Just keep the state in a variable and check whether the animation run already or not.
