### ISSUE TITLE
Scrolling in react application with pagepiling.js

### ISSUE THREAD

**Issue by MohammedSayeem** [alvarotrigo/pagePiling.js#238]
when scrolling in react application my UI moves to section other than next section which is not expected behaviour of pagepiling.js.
Is there anything i can do to stop this from happening?

**Comment by alvarotrigo** [comment]
Have you tried [fullPage.js](http://alvarotrigo.com/fullPage/) instead?

It has a similar effect but it comes with plenty more options to deal with modals or scrolling elements placed on top. 

It also has a wrapper for React. 
https://alvarotrigo.com/react-fullpage/

pagePiling.js is not actively maintained anymore.

**Comment by MohammedSayeem** [comment]
Thanks for the help.
Will try the same on Full page.js diligently.

**Comment by MohammedSayeem** [comment]
Hi again,
Since fullpage.js is a paid resource, i wont be able to afford currently,
is there any way i can do it in pagepiling.js itself?

**Comment by alvarotrigo** [comment]
Everything is possible with the right knowledge :)
But I can't help you here I'm afraid. 

I hope you find your way!
