### ISSUE TITLE
Difference between pagePiling and fullPage?

### ISSUE THREAD

**Issue by mhulse** [alvarotrigo/pagePiling.js#31]
> [I guess you meant pagePiling.js](https://github.com/alvarotrigo/pagePiling.js/issues/29#issuecomment-64825045)

Just out of curiosity, what's the difference between `pagePiling.js` and `fullPage.js`?

https://github.com/alvarotrigo/fullPage.js

Are there use cases for when I'd use one over the other?

Wondering if the READMEs should mention each other as they look similar in functionality; it might be cool to have a section that gives use cases, like:

> This project is based on XXXX; you would use pagePiling.js if you want to do ZZZZ, otherwise use fullPage.js to do YYYYY

… or something like that. :smile: :+1: 

In other words, I'd be curious to know which came first and why you decided to branch them into two different code bases.

Awesome plugins btw, thanks!

**Comment by alvarotrigo** [comment]
It is not about being more or less complex...

They are two different plugins with two different purposes. Choosing one or the other depends on the designer and their taste.

**The animation is different...**
fullPage.js is an scrolling plugin. The site scrolls up or down. 
pagePiling.js is an stack of pages. The page doesn't scroll like a carousel, it reveals the page behind the current one.Only one page moves, the other stays static. 

**The navigation is different**
fullpage.js scrolls from origin to destiny showing all the sections in the middle.
pagePiling.js goes directly to the page you want. Go from section 1 to section 3, for example.

**Horizontal slides**
fullPage.js provides a way to create horizontal slides.
pagePiling.js doesn't.


--- 
Update 2025:

Now, I'd say the biggest difference is that pagePiling.js is discontinued, and fullPage.js isn't.

fullPage.js is way more complete than pagePiling.js and includes tens of options that pagePiling.js doesn't.
From responsive options, to scroll inside sections, extensions, lazyload, etc.

**Comment by MerantauWarrior** [comment]
You said :
"Horizontal slides
fullPage.js provides a way to create horizontal slides.
pagePiling.js doesn't."
If I use it with Bootstrap built-in carousel may it help me create horizontal slides?

**Comment by alvarotrigo** [comment]
> If I use it with Bootstrap built-in carousel may it help me create horizontal slides?

You might have troubles with touch devices.

**Comment by MerantauWarrior** [comment]
Can I solve them with some extra JS code and if yes can you ask where to find it.. I just like the way it goes from page to page(1 to 3 for example ) in pagePiling.js.
BTW can I build something like this https://blogun.ru/ with fullPage.js?

**Comment by alvarotrigo** [comment]
> Can I solve them with some extra JS code and if yes can you ask where to find it.. I just like the way it goes from page to page(1 to 3 for example ) in pagePiling.js.

You might have to modify the plugin. 


> BTW can I build something like this https://blogun.ru/ with fullPage.js?

I don't see why not.
