### ISSUE TITLE
Pagepiling.js auto-scrolling on IE with touch-screen

### ISSUE THREAD

**Issue by BenComicGraphics** [alvarotrigo/pagePiling.js#34]
fngeats.com, IE11, if the cursor is near the top or bottom of the page, it causes the page to autoscroll to the previous or next locations.  NEED IMMEDIATE HELP!

**Comment by alvarotrigo** [comment]
You IMMEDIATE need to update your version of pagePiling.js because you are using quite an old one...

**Comment by BenComicGraphics** [comment]
Updated.  Still doing it.  Reopen

**Comment by alvarotrigo** [comment]
You are probably using a computer with a touch screen, please see [this topic](https://github.com/alvarotrigo/fullPage.js/issues/904).

I would recommend you to deactivate the touch feature while the problem get solve.

**Comment by BenComicGraphics** [comment]
Client has a touchscreen computer.  need some more help than that.  Thanks!

**Comment by alvarotrigo** [comment]
If you really need it as soon as possible [send me a mail](http://alvarotrigo.com/#contact-page) and we can talk about it.

**Comment by alvarotrigo** [comment]
Solved in the latest release v 1.2.
