### ISSUE TITLE
Stop pagepiling after second section

### ISSUE THREAD

**Issue by Fl0rianFischer** [alvarotrigo/pagePiling.js#36]
Hey, I'm quite a beginner and I'm having trouble with the following issue:

I want the pagepiling effect only to work on the first section, after that I want a normal scroll. My markup looks like this (with brackets obviously):

div id="pagepiling"
    div class="section
       Logo content
    /div

   div class="section"
      Rest of the page
   /div
/div

Would be very grateful for a tip!

Florian

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such an option.
You might be able to do it by using the function `setAllowScrolling ` combined with some other plugin such as  `slimScroll`.

If you don't know how to do it and you really need it, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by Fl0rianFischer** [comment]
Thanks a lot for your answer and for this really great plugin as well!
