### ISSUE TITLE
Youtube video overlapping in IE

### ISSUE THREAD

**Issue by Ty-u** [alvarotrigo/pagePiling.js#37]
Hi, I'm currently trying to build a website using pagePiling.js, and I put a video in like the 3rd section, and it works well on all browsers except IE (latest version), where the video is shown overlapping over everything on the first section?

I first thought of avoiding this issue by using fullPage.js instead, but in the end the navigation really looks better with a stacking system.

I also tried putting the video in a z-index but it doesn't change anything.

Do you know what could cause this?

**Comment by alvarotrigo** [comment]
Could you reproduce it somewhere or post a link to your site so I can take a look at it?
Which version of IE are you using? It seems to work well on IE 9 and 8.

**Comment by Ty-u** [comment]
I'm using IE 11.
Here's an example using your demoPage.html, I just added a 5th section with a basic youtube video in it. Works fine on Chrome and Firefox, overlapping everything on IE.
http://bit.ly/1D1Vhla

**Comment by alvarotrigo** [comment]
Nothing to do with pagePiling.js:
http://stackoverflow.com/questions/9074365/youtube-video-embedded-via-iframe-ignoring-z-index

Its a problem with iframes and z-index in IE.

**Comment by Ty-u** [comment]
Thanks a lot!
