### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by Gallitin** [alvarotrigo/pagePiling.js#38]
If I don't define names for the tooltips then they show up "undefined". 

How can I disable the tooltips altogether?

**Comment by alvarotrigo** [comment]
It shouldn't happen. I'm not able to reproduce it [in this fiddle](http://jsfiddle.net/97tbk/476/). 
Please add the initialization that you are using.

Which browser are you using and which version of it?

**Comment by alvarotrigo** [comment]
Yeah, thanks for reporting it.

**Comment by alvarotrigo** [comment]
Solved in the latest release 1.2.

**Comment by Gallitin** [comment]
Great, will test with newest version, thanks!
