### ISSUE TITLE
How can I keep my old school nav bar and footer on top of the pages?

### ISSUE THREAD

**Issue by HelenCR** [alvarotrigo/pagePiling.js#39]
Hi.

I love this effect, it looks really good and is a nice point of difference to onepage which I am seeing everywhere.

This is basically my first attempts to use javascript and jquery, and my project is still in development. 

I want my nav bar and footer to stay on top of the pages.  I am using z-index and position fixed which works when at the top for nav bar and bottom for footer but not both at the same time or while on intermediate pages.

http://www.helencrolls.com/

Any help with this would be much appreciated.

**Comment by alvarotrigo** [comment]
Remove your padding and margin from sections. You should be careful when modifying the default styles for them.
