### ISSUE TITLE
Scrollable Feature Not Working

### ISSUE THREAD

**Issue by McCarraDev** [alvarotrigo/pagePiling.js#41]
I am using all of the updated js/css and am trying to use the scrollable feature by adding the "pp-scrollable" class to the section I want to us as so:

````
<div class="section pp-scrollable">
````

However it still continues to scroll past the whole section the second I start scrolling. 

I even tried setting the height of the section to be a good amount bigger than the screen height and still nothing. Any idea why?

Thanks!

**Comment by alvarotrigo** [comment]
Are you using the latest version 1.5? Check it in case, because I updated it yesterday.

**Comment by alvarotrigo** [comment]
Right. I've just noticed a little bug [while trying to reproduce your problem](http://jsfiddle.net/hrrLvd2a/20/).
It is only working at the moment when using the option `verticalCentered:false`.

I'll fix it in a few minutes.

**Comment by alvarotrigo** [comment]
Ok, solved in the last version 1.5.1

**Comment by McCarraDev** [comment]
Thank you very much sir! Awesome plugin, thanks for developing it!

**Comment by fourroses666** [comment]
Was looking for this! Adding the "pp-scrollable" makes longer pages scrollable 👍
