### ISSUE TITLE
scrolling inside sections and cant resize the container of it

### ISSUE THREAD

**Issue by gonyot** [alvarotrigo/pagePiling.js#43]
Hi. I'm trying to make a scrolling inside a section like below.

HTML:

div id="pagepiling"
    div class="section pp-scrollable"
        div id="#section-1-piling"
        	div class=".section-1-container"
        		content 1 of the first section
        	/div
        	div class=".section-1-container"
        		content 2 of the first section
        	/div
        	div class=".section-1-container"
        		content 3 of the first section
        	/div
        	div class=".section-1-container"
        		content 4 of the first section
        	/div
        /div
    /div
    div class="section pp-scrollable pt70" id="section3"
        content 2 of the second section
    /div
    div class="section" id=""
       content 3 of the third section
    /div
/div

JAVASCRIPT:
script type="text/javascript"
('#section-1-piling').pagepiling({
	    sectionsColor: ['#ccc', '#00f', '#fff'],
	    sectionSelector: '.section-1-container',
	    navigation: {
	    	'position': 'right',
	   		'tooltips': ['Page 1', 'Page 2', 'Page 3']
	   	}
	});
/script
It will work but not the thing I want because when I scroll up, it will go on the second section not inside the first section. I'm trying to make a piling slider inside a pagepiling but it seems that I cant make it work. Can you give me some advise on how to do it? thanks.

**Comment by alvarotrigo** [comment]
Sorry I don't understand your question. Try to explain it in another way.

**Comment by gonyot** [comment]
Hi. Sorry for my bad english. I'm currently making a micropage using pagepiling. My first section contain a smaller/mini version of pagepiling which is inside a div container (the size probably 800x600). I just changed the class name of the mini version of pagepiling but it is not working. Everytime I've tried to scroll in the mini version, it will scroll the whole first section and will move to the next section. That is what I'm trying to make. Do you have any advise or the plugin doesnt support something like this?

**Comment by alvarotrigo** [comment]
I dont understand what you mean when you say:

> I just changed the class name of the mini version of pagepiling

**Comment by alvarotrigo** [comment]
I dont understand what you mean when you say:

> I just changed the class name of the mini version of pagepiling

**Comment by alvarotrigo** [comment]
I dont understand what you mean when you say:

> I just changed the class name of the mini version of pagepiling

**Comment by KRVPerera** [comment]
May be its very old..
But I think he has two pagepiling sections one is within another and he wants to first scroll the mini (inside) and after that it should trigger the outer scroll.. But the problem is it always scroll the outer one
