### ISSUE TITLE
Using iframes

### ISSUE THREAD

**Issue by har9** [alvarotrigo/pagePiling.js#45]
As shown below, can't I use iframes to display my other html pages? After I insert the iframe tag, page2 and page3 are lost. Please help!!

<div id="pagepiling">
	    <div class="section" id="section1">
	    	<h1>pagePiling.js</h1>
                <iframe src="home.html" width="1300px" height="380px"/>
	    </div>
	    <div class="section" id="section2">
	    	<div class="intro">
	    		<h1>Backgrounds </h1>
	    		<p>Show it in full screen!</p>
	    	</div>
	    </div>
	    <div class="section" id="section3">
	    	<div class="intro">
	    		<h1>Just terrific!</h1>
	    		<p>Use the power of images</p>
	    	</div>
	    </div>
	</div>

**Comment by alvarotrigo** [comment]
pagePiling won't lead with iframes. 
If you want to use them you would have to deal with them by yourself I'm afraid.

**Comment by har9** [comment]
Oh thanks a lot for the quick reply! If I want to link it with the html pages I have, is it possible?
