### ISSUE TITLE
QUERY: when I fill a slide with lots of text Im seeing strange render effects on scroll

### ISSUE THREAD

**Issue by kafisher9** [alvarotrigo/pagePiling.js#49]
Will update with live URL so you can see what i mean but thought Id report.

**Comment by alvarotrigo** [comment]
Can't provide any solution or investigate the error unless you provide a reproduction of your problem.
I'll close till then.

**Comment by k8fisher9** [comment]
Hi 

apologies for the delay I didnt have the link on me. So an instance where it works really nicely for us (like all the examples Ive seen online): http://uat2.clsl.co.uk/

An example with text in situ in the slides which was exhibiting the behaviour right up till I went to paste this link (seems to have cleared with a fresh load of firefox / chrome which is weird: 
http://uat2.clsl.co.uk/development/risk-appraisal#three

Very strange Id not noticed shutting the browser seems to clear the issue. Which is great but also kinda strange.

I guess ermm, Ive no idea why closing a browser entirely would clear the problem, strange.

Kate

**Comment by alvarotrigo** [comment]
I can not see any strange render anywhere. Tested in Chrome, Firefox.
