### ISSUE TITLE
setTimeout mousescroll conflict

### ISSUE THREAD

**Issue by adamstar83** [alvarotrigo/pagePiling.js#53]
Hello Alvaro!

Appreciate your work on this! I'm using your plugin as part of the UBER theme: http://themeforest.net/item/uber-minimal-multiconcept-portfolio-template/10015050

When I add a timeout as outlined here: https://github.com/alvarotrigo/multiscroll.js/issues/22

All is fine and good until I scroll with the mouse. Then sections scroll through in rapid speed, sometimes two or three sections scroll through on top of the other.

Wondering if you could assist.

Thanks!

**Comment by alvarotrigo** [comment]
Use [`setAllowScrolling(false)`](https://github.com/alvarotrigo/pagePiling.js).
