### ISSUE TITLE
How to target nextIndex

### ISSUE THREAD

**Issue by ltwmaster** [alvarotrigo/pagePiling.js#54]
Hey :) Great script, I really love it!

Got some deeper questions:
How can I target nextIndex (the section that I am scrolling to?)
In my "onLeave", I want to target the nextIndex, whatever Index that may be, something like: 
$(nextIndex).animate({opacity: 1}, 50)}

But in my case I always need to target the class or ID its self, which is kind of not a good solution. 

Thanks in advance!

**Comment by alvarotrigo** [comment]
Use: `"('.seciton').eq(nextIndex).animate(....)`

**Comment by ltwmaster** [comment]
Great, thanks!

**Comment by alvarotrigo** [comment]
Updated the answer.
