### ISSUE TITLE
Triggering $.fn.pagepiling.setAllowScrolling(true); from outside

### ISSUE THREAD

**Issue by ltwmaster** [alvarotrigo/pagePiling.js#56]
Hi,

Sorry for the many questions, I will leave a donation tonight.. 

Quick question: 
How can I trigger $.fn.pagepiling.setAllowScrolling(true); from another event? 
Once I reach the last pile, I deactivate setAllowScrolling, but when a certain element is out of view I want to allow it again. 

How can it be triggered within another function that is outside of the pagepiling({}) function?

Cheers, 
Lasse

**Comment by ltwmaster** [comment]
For anyone else wondering: Calling the function outside the pagepiling function did work in the $(document).ready(), so I just did it in there.

**Comment by alvarotrigo** [comment]
> How can it be triggered within another function that is outside of the pagepiling({}) function?

You can trigger it from anywhere if the plugin was initialized.

**Comment by ltwmaster** [comment]
Hey Alvaro,

I get this error: 
Uncaught TypeError: Cannot read property 'pagepiling' of undefined

Code in this case is:

function isElementVisible(elementToBeChecked)
{
    var TopView = jQuery(window).scrollTop();
    var BotView = TopView + jQuery(window).height();
    var TopElement = jQuery(elementToBeChecked).offset().top;
    var BotElement = TopElement + jQuery(elementToBeChecked).height();
    return ((TopElement >= TopView));
}


 jQuery(window).scroll(function () {
       isOnView = isElementVisible("#pagepilingfooter");
       if(isOnView){
		   $.fn.pagepiling.setAllowScrolling(false);
		  } 
		   })
		   
 jQuery(window).scroll(function () {
       isOnView = isElementVisible("#pagepiling");
       if(isOnView){
		   $.fn.pagepiling.setAllowScrolling(true);
		   
		  } 
		   })

**Comment by alvarotrigo** [comment]
That's a matter of javascript knowledge. You'd better ask in other place such as stackoverflow.com
