### ISSUE TITLE
Sub sections

### ISSUE THREAD

**Issue by frontenddevguy** [alvarotrigo/pagePiling.js#57]
Hi, I have been given a design to build that requires sub sections, and extra dots that appear and are highlighted as in the image. Is this possible?
![screen shot 2015-06-29 at 15 01 28](https://cloud.githubusercontent.com/assets/3789940/8409457/f4544d54-1e6f-11e5-8d67-18f1cc15cec7.png)

**Comment by alvarotrigo** [comment]
I'm afraid the plugin doesn't provide such an option.

**Comment by frontenddevguy** [comment]
Does any such functionality exist anywhere on the web? I bet it does but couldnt find any examples or plugins that deal with this scenario

**Comment by alvarotrigo** [comment]
No idea.
