### ISSUE TITLE
I want to use this effect in the middle of the page

### ISSUE THREAD

**Issue by Rekha1234** [alvarotrigo/pagePiling.js#60]
I liked this effect a lot but when i am trying to use it in my page which is having header and footer, the effect is overlapping the header. Is there any way i can use in the middle of the body inside some div?

Also its taking full screen and i am using bootstrap container in my page. i want this effect to be shown inside the container div

**Comment by alvarotrigo** [comment]
Take a look at an example of usage here: http://www.facebookgroups.com/

Use `fixed` positioned header and footer.
