### ISSUE TITLE
Using pre tag makes the content appear across all slides

### ISSUE THREAD

**Issue by madhavan020985** [alvarotrigo/pagePiling.js#61]
Thanks a lot for this framework.. It is very simple and doesn't meddle much with my own css properties...

I face one problem, when one of my slides/sections contain a pre element. That element gets rendered on top of all the slides. I am using pre element since it is a yaml format that needs to have its spaces preserved.

It looks like (the dark bordered line contains the spilled contents),
![page-piling](https://cloud.githubusercontent.com/assets/4812767/8999628/c491f338-375a-11e5-9ac7-98018be56d0d.png)

My code is @ https://github.com/madhavan020985/bangpy-aug-saltstack/blob/master/index.html#L46

**Comment by alvarotrigo** [comment]
Please reproduce the issue in jsfiddle or codepen for further investigation. 
Closed until then.
