### ISSUE TITLE
Multiple piling on single page.

### ISSUE THREAD

**Issue by tezro** [alvarotrigo/pagePiling.js#66]
Hi there, is there a way to create more than one piling container on one page? So that it look like something like this structurally. I'd control which container to show, say, from another/custom menu.

```
+ pile 1
    - section 1-1
    - section 1-2
    - section 1-3
+ pile 2
    - section 2-1
    - section 2-2
    - section 3-3
...
```

Or maybe there's a way to destroy and reinitialize the pagePiling?

Thanks ahead.

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any option for it.
