### ISSUE TITLE
Multiple piling issue with angular

### ISSUE THREAD

**Issue by Nappp** [alvarotrigo/pagePiling.js#67]
I'm using Angular with ng-route to render a single page application with multiple pages, each page have a different Pagepiling. The problem is at <code>line 810</code>.
```
 function addVerticalNavigation(){
    $('body').append('<div id="pp-nav"><ul></ul></div>');
    var nav = $('#pp-nav');
    ...
```
Simple add an element to body with out judging will cause nav-btns collapses with the previous dots, and the solution is simple enough:
```
 function addVerticalNavigation(){
    $('#pp-nav').remove();
    $('body').append('<div id="pp-nav"><ul></ul></div>');
    var nav = $('#pp-nav');
    ...
```
Cheers

**Comment by alvarotrigo** [comment]
It seems you are initializing pagePiling.js multiple times... 
Your solution is nothing but a hack which doesn't really solve the real problem. 

You should only initialize pagePiling.js once.
