### ISSUE TITLE
Fading in horizontal slide 

### ISSUE THREAD

**Issue by cinghaman** [alvarotrigo/pagePiling.js#69]
Has anyone tried to use effect: fade, instead of ease: swing, after adding jquery UI, is it possible to do it? as i dont want the slides to swing by instead just fade?

**Comment by alvarotrigo** [comment]
pagePiling doesn't provide such an option and it is not a trivial thing to do. 
I'll close the issue as this forum is to treat pagePiling.js bugs or usages of existent features.

**Comment by cinghaman** [comment]
but can be labeled as enhancement or may be a pointer as to how to accomplish it if one doesnt want just simple swing/linear effect but add more filters like fade

**Comment by alvarotrigo** [comment]
I'm afraid it won't be done in pagePiling.js.
There are plenty of sliders out there which can help you to create a fade transition. I doesn't make sense to implement it in pagePiling.js.
