### ISSUE TITLE
How to place the navigation dots bottom in horizontal mode

### ISSUE THREAD

**Issue by DingJunyao** [alvarotrigo/pagePiling.js#70]
In horizontal mode, the navigation dots are still in the right of the page. I tried to set the position of the navigation to "bottom",but it doesn't work. Does pagePiling.js have the function to place the navigation dots bottom? If so, how to achieve it?

**Comment by alvarotrigo** [comment]
It doesn't provide a way to do it at the moment. 
But you probably can do it with CSS very easily:

#pp-nav{
    margin: 0 auto !important;
    left:0;
    right: 0;
    top: auto;
    bottom: 17px;
    display: inline-block;
}
#pp-nav li, .pp-slidesNav li{
    display:inline-block;
}

**Comment by Sneakyp33t** [comment]
is there a way to have the dot on 2 places? I was a set of the dots on the left and right side of the page

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such an option I'm afraid.
