### ISSUE TITLE
Full background video - overlapping on to next slide

### ISSUE THREAD

**Issue by keljnr** [alvarotrigo/pagePiling.js#72]
Hi,
I'm having display issues with full page bg video. The video seems to overlap on to the next slide on certain resolutions/ratios.

Please see image:
![pagepiling](https://cloud.githubusercontent.com/assets/13959740/9462275/8e5efb42-4b0c-11e5-9294-24133d24a900.jpg)

This is directly from the demo site. As you can see the left screen (1920 x 1080) shows a small amount off video overhang... whilst the right displays perfectly.

Any thoughts on how this can be fixed?

Many thanks.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/pagePiling.js/issues/65
