### ISSUE TITLE
section selector overlaps Blogger selector

### ISSUE THREAD

**Issue by absurdevolution** [alvarotrigo/pagePiling.js#73]
I'm trying to install pagePiling.js on blogger and am running into problems with overlapping selectors. I am looking at the code now and it looks like i could siimply change the sectionSelector: .'section' to something lie '.stacks' to work around. Would I then have to change the section selector throughout the JS as well? ie:

PP.moveStacksUp = function () {
            var prev = $('.pp-stacks.active').prev('.pp-stacks');

**Comment by alvarotrigo** [comment]
Nop. Just use the `sectionSelector`.
