### ISSUE TITLE
Full background videos have a bug about scrolling

### ISSUE THREAD

**Issue by say8425** [alvarotrigo/pagePiling.js#75]
![2015-10-06 2 09 47](https://cloud.githubusercontent.com/assets/3258867/10300629/0bff6ab2-6c34-11e5-8838-ae43ababcb6f.png)

Hello. I use pagePiling greatly. But I found bug about full background video.<br>

I code with full video background. And I can found the video background does not scroll completely. And I can found same issue in Live demo.<br>

After little time, in OS X 10.11 found this issue can be found only Chrome. Safari and Firefox does not. Windows and Linux, I don't know cause I don't have that platform. In this case, browser's height is low then you can found it. If height is high, then this issue is not occurred.<br>

**Comment by say8425** [comment]
I've found `object-fit: cover;` make this issue. We need another alternative tag maybe.

**Comment by say8425** [comment]
I think it related with this issue. http://stackoverflow.com/questions/30700144/responsive-object-fit-cover-fix-on-chrome

**Comment by alvarotrigo** [comment]
Use the css property `overflow:hidden` for section elements. 
Not  a bug in the plugin in any case, it is a matter of design. The example is not perfect.
