### ISSUE TITLE
smooth scroll to anchors on normal scroll section

### ISSUE THREAD

**Issue by salmanpatnee** [alvarotrigo/pagePiling.js#76]
Hey Alvaro you  have done a great job, I'm using your plugin and i've just made a site like hugein first section is the full and then normal scrolling. i have different section in normal scrolling section that have anchors on them and ofcourse i have menu. i want to scroll there smoothly i am implementing a code but this is not working why? here is the code 

```javascript
$(function() {
  $('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
```

**Comment by alvarotrigo** [comment]
You'd better ask about javascript in other place such as stackoverflow.com
This forum is to treat pagePiling.js problems.

**Comment by salmanpatnee** [comment]
It is working all other places but it fails on pagepiling. why?

**Comment by alvarotrigo** [comment]
Probably the translate3d applied to the plugin.
Try using `css3:false` in pagePiling,js

**Comment by salmanpatnee** [comment]
Yes it is already false but not working I'm worrying  what to do now

**Comment by alvarotrigo** [comment]
Sorry yours is not a pagePiling.js problem but a very specific one with your own code. If you need my help [contact me](http://alvarotrigo.com/#contact-page) to ask for support.
