### ISSUE TITLE
onEnter function? 

### ISSUE THREAD

**Issue by tb9jen** [alvarotrigo/pagePiling.js#77]
Hi there, I see you have an onLeave function, but I need to activate something AFTER the transition has occurred (another scrolling function, so they both occur at the same time currently) , and I was wondering if at some point you'd consider adding an onEnter function?

**Comment by alvarotrigo** [comment]
`afterLoad` is what you are looking for.

**Comment by tb9jen** [comment]
Oh, haha thanks! I guess I misunderstood what that did.
