### ISSUE TITLE
Custom animation not working inside the sections?

### ISSUE THREAD

**Issue by Ansif** [alvarotrigo/pagePiling.js#78]
Hi,

Thanks a lot for this plugin! :)

I want to use [animate.css](http://daneden.github.io/animate.css/) with [wow.min.js](http://mynameismatthieu.com/WOW/) plugin. But it's not working within your section scroll?
Can you please let me know the solution of how to fix this issue. I need to finish this project asap.

Animation is loading but the main issue is, for a normal pages when we scroll that section animation will load. Because, it'll wait until we scroll that section. But here in this case sections are loading without scroll. So, if i add animation in 3rd section. It loads instantly, so users not able to see that animation when they scroll to that section! 

So, any of suggestion is highly appreciated! :)

Regards,
Ansif

**Comment by alvarotrigo** [comment]
You can read the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions). Many of them are the same for pagePiling.js.

Basically, the scroll event won't get fired because of the way the plugin works.
