### ISSUE TITLE
Test if section is active.

### ISSUE THREAD

**Issue by steamsynthetic** [alvarotrigo/pagePiling.js#79]
Hi there. I am trying to do a test to see if another section is active in jQuery to load various animations and other content. However, jQuery doesn't seem to like to test if the section is active.

if ($('section#location').is(".active")) { 
     console.log('true');
}

if ($('section#location').has(".active")) { 
     console.log('true');
}
if ($('section#location.active') === true){
    console.log('true');
}

I have tried these within document.ready, window.load, and document.change functions. But testing with jQuery will not load any other scripts because on the pagePilling document will not tell the browser that the elements have an active state when they do.

**Comment by alvarotrigo** [comment]
I don't know what you are trying, but this will work for sure once pagePiling.js has been initialized:

```javascript
if ($('#section2').has('active')) { 
```

**Comment by steamsynthetic** [comment]
That is registering every section to have an active class when they do not.
The sites on a test server, so feel free to look at it.
http://m-theparkbankershill.blu-site.com/

Current code is in the js file. 
(its a tad messy, but its just in development)
http://m-theparkbankershill.blu-site.com/wp-content/themes/the-park-mobile/js/init.js?ver=1.0.0

I loaded the jQuery test just after the pagePiling

**Comment by alvarotrigo** [comment]
> That is registering every section to have an active class when they do not.

I don't know what you are talking about. 
That's the way to check if they are active or not.

**Comment by steamsynthetic** [comment]
Sorry, I resolved this issue through ajax. Thanks again though.

**Comment by MarkDat** [comment]
i think you should try  below:
$('section#location').hasClass('active')
