### ISSUE TITLE
Sorry, can't open back up issue from thread.

### ISSUE THREAD

**Issue by steamsynthetic** [alvarotrigo/pagePiling.js#80]
https://github.com/alvarotrigo/pagePiling.js/issues/79

Update:
The code you commented is registering every section test to have an active class when they do not.
The sites on a test server, so feel free to look at it.
http://m-theparkbankershill.blu-site.com/

Current code is in the js file. 
(its a tad messy, but its just in development)
http://m-theparkbankershill.blu-site.com/wp-content/themes/the-park-mobile/js/init.js?ver=1.0.0

I loaded the jQuery test just after the pagePiling

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/pagePiling.js/issues/79
