### ISSUE TITLE
Mobile Browsers

### ISSUE THREAD

**Issue by steamsynthetic** [alvarotrigo/pagePiling.js#81]
On mobile browsers, the browsers navigation bar, and on mobile safari bottom navigation bar stay visible the whole time. Is there a setting or function that needs to be in place to show. Image attached.

![img_0412](https://cloud.githubusercontent.com/assets/1971680/10985358/e81e4b4c-83dd-11e5-8cef-ee1b5c69c4a0.jpg)

**Comment by alvarotrigo** [comment]
Please check [this same topic on fullpage.js plugin](https://github.com/alvarotrigo/fullPage.js/issues/896), same can be applied for pagePiling.js

There's no solution for it.
