### ISSUE TITLE
Drop fullpage idea on mobile, but preserve functions

### ISSUE THREAD

**Issue by El-Rico** [alvarotrigo/pagePiling.js#84]
It works great on desktop! But I'd rather **drop the fullpage idea on mobile phones** and scroll normally, because of the lack of space on small screens.

I fixed this now by not initialising the pagepiling plugin at all if the screen is smaller then 767px in width. Sad thing is... All my navigation buttons stopped working, because I can't use the _$.fn.pagepiling.moveSectionDown();_, _$.fn.pagepiling.moveSectionUp();_, _$.fn.pagepiling.moveTo(3);_ anymore.

And that's really nasty... Looking for a responsive fallback option like **responsiveFallback: '767'** that provides default/native OS scrolling with navigational functions still intact.

Other than this isue... Amazing plugin alvarotrigo

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any responsive option at the moment. 
I'll mark it as an enhancement for possible future versions. 

If you really need it now, [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by TAVENIER-Gabriel** [comment]
Hello, 
Thank you for this plugin, it works great. But, like El-Rico, I need to desable it on little screen. Could you create a fallbak option for this ?

**Comment by traf** [comment]
+1 to disable the plugin on mobile.

**Comment by alvarotrigo** [comment]
I had no idea this issue still open!! My bad!

@traf did you check the responsive options available now 3 years after the question and my answer were made?
Check the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) where you'll find `responsiveWidth`, `responsiveHeight`, `fp-auto-height-responsive` etc.

**Comment by alvarotrigo** [comment]
Oh. This is about pagePilings :)

I would recommend you to change to fullPage.js (my other library) that provides plenty of more options, and within them, the responsive ones.

You can emulate the pagePiling.js effect by using the [Parallax extension](https://alvarotrigo.com/fullPage/extensions/parallax.html) with offset 100% as I detailed in [this blog post.](https://alvarotrigo.com/blog/how-create-tumblr-website-effect/)

**Comment by Niremizov** [comment]
+1

**Comment by 0divider** [comment]
+1
