### ISSUE TITLE
Bootstrap & pagePiling - Won't scroll past 3rd "page"

### ISSUE THREAD

**Issue by jsmerg** [alvarotrigo/pagePiling.js#85]
Hi there, 
I've been through my site over and over and I cannot find an error in my code (or I just don't see it). I'm using bootstrap and I'm wondering if there is possibly a conflict?

Everything on the site works as it should until you try to scroll past the 3rd page or section. It just won't scroll. If you click on the navigation dot it moves but the background image isn't the one declared in the css. (Note: it's not completed yet and the load is crap - but I'm trying to get through this issue first)

The url for the site is www.action-for-animals.com, but I've attached my files as well. Any insight is so appreciated! It could very well be something I'm missing too - just covering the bases. 

Cheers!
[sitecss_html.docx](https://github.com/alvarotrigo/pagePiling.js/files/64868/sitecss_html.docx)

**Comment by alvarotrigo** [comment]
Chrome inspector reveals why.
You have some funny `em` elements in there that shouldn't be there. 

![em](https://cloud.githubusercontent.com/assets/1706326/11866942/09cf6378-a4a6-11e5-9949-d05fa1e7bed1.PNG)

**Comment by jsmerg** [comment]
ah You know what I think it's an unopened em tag. Good grief it's always the stupid little things that take ya down!

Thanks for taking a look!

**Comment by alvarotrigo** [comment]
Not really. There can not be any element between sections. You would have to remove the `em`.
