### ISSUE TITLE
Disable keyboard-scrolling while typing in a textarea / input

### ISSUE THREAD

**Issue by El-Rico** [alvarotrigo/pagePiling.js#86]
I'm unable to use the navigational arrows while typing in a form. When i press UP, DOWN, LEFT, RIGHT, HOME, etc. the pages start scrolling.

Would be great if that functionality stops while a input or a textarea is focussed.

**Comment by alvarotrigo** [comment]
I'll mark it as an enhancement. 
If you really need it as soon as possible [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by wisniewski94** [comment]
Bump

**Comment by wisniewski94** [comment]
`$('input').click(function() {
        if ($(this).is(':focus')) {
            $.fn.pagepiling.setKeyboardScrolling(false);
        }
    })`

This is the best solution. Hope it helps!
