### ISSUE TITLE
scroll error on macbook trackpad

### ISSUE THREAD

**Issue by Jossnaz** [alvarotrigo/pagePiling.js#87]
the scroll error occurs when on the alvarotrigo site http://alvarotrigo.com/pagePiling/ I scroll down on my macbook trackpad to the fourth page and then attempt to scroll again - it takes me back to the third page, and then to the fourth http://jmp.sh/oOKku7C
I was unable to reproduce this here: http://www.alvarotrigo.com/fullPage/#secondPage
this also occurs occaisonally on the third (final) page without scrolling again
you scroll 1 then 2 then 3, then pause as if to read the third slide, but it goes back to the second slide

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 
I have the impression I also experienced that at some point. I'll check it whenever I have access to a MacBook.

**Comment by eliawk** [comment]
same problem here!

**Comment by sonidiaz** [comment]
Replace this function in line 561

function MouseWheelHandler(e) {
            if(!isMoving()){
                // cross-browser wheel delta
                e = window.event || e;
                var delta = Math.max(-1, Math.min(1,
                        (e.wheelDelta || -e.deltaY || -e.detail)));

                var activeSection = $('.pp-section.active');
                var scrollable = isScrollable(activeSection);

                //scrolling down?
                if (delta < 0) {
                    scrolling('down', scrollable);

                //scrolling up?
                }else {
                    scrolling('up', scrollable);
                }


                return false;
            }
         }

for this:

function MouseWheelHandler(e) {
            if(!isMoving()){
                // cross-browser wheel delta
                e = window.event || e;

                var tdelta = (e.wheelDelta || -e.deltaY || -e.detail);
                if(tdelta !== 0){
                    var delta = Math.max(-1, Math.min(1, tdelta));
                } else {
                    return false;
                }


                var activeSection = $('.pp-section.active');
                var scrollable = isScrollable(activeSection);

                //scrolling down?
                if (delta < 0) {
                    scrolling('down', scrollable);

                //scrolling up?
                }else {
                    scrolling('up', scrollable);
                }


                return false;
            }
         }

**Comment by Jossnaz** [comment]
I actually pulled the plug on pagePiling.js, it is just not a viable solution if what, all mac books are buggy.
A solution for me was this:
https://github.com/peachananr/onepage-scroll

i am not posting it to pull away users from your plugin. But I am sure you can let yourself get inspired by their solution. And for the others, use this plugin until u implemented a solution.

**Comment by alvarotrigo** [comment]
> I actually pulled the plug on pagePiling.js, it is just not a viable solution if what, all mac books are buggy.

@Jossnaz the bug was not there originally and it seems it has been introduced due to some browsers' update. 
In any case, if you want a similar solution similar to the one you posted, you can go for [fullPage.js](http://alvarotrigo.com/fullPage/) (which I also created) if you want a more compatible (IE8 included) reliable and configurable solution.

**Comment by alvarotrigo** [comment]
Solved in pagePiling.js 2.5.3. Please update.
