### ISSUE TITLE
Animation effect

### ISSUE THREAD

**Issue by hassanasad** [alvarotrigo/pagePiling.js#94]
First of all - Love your work!!

Its very neat and clean and does what it say. I was just wondering if it would be possible to invert the overlay effect? For example, instead of moving the section upwards, load one from bottom on to top?

**Comment by alvarotrigo** [comment]
Thanks I'm glad you find it useful!
And nop, I'm afraid the plugin doesn't provide such option.

Feel free to [contact me](http://alvarotrigo.com/#contact-page) for a customization if you really need it.

**Comment by MladenJanjetovic** [comment]
This would be nice

**Comment by piotrkunicki** [comment]
@alvarotrigo is it possible to change the animation effect? I.e. use the fade out/in instead of sliding?

**Comment by alvarotrigo** [comment]
@piotrkunicki you can use my other library instead, [fullPage.js](https://alvarotrigo.com/fullPage/) and use the [fading effect extension](https://alvarotrigo.com/fullPage/extensions/fading-effect.html) to get that result.

**Comment by piotrkunicki** [comment]
@alvarotrigo thanks, but with fullPage.js is it possible to create scrollable section, like with pagePilling?

**Comment by alvarotrigo** [comment]
See the docs regarding scrollOverflow. And the [example online](https://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by MickL** [comment]
Would be nice to have a configuration option, e.g. the next slide should come in from bottom instead of the current slide removes to top or have both slide up like fullPage.js does.
