### ISSUE TITLE
Change horizontal default direction (from "left to right" to "right to left")

### ISSUE THREAD

**Issue by diegopolido** [alvarotrigo/pagePiling.js#96]
Is that possible to invert the horizontal direction (from "left to right" to "right to left")?

I appreciate your help.

Thanks!

**Comment by alvarotrigo** [comment]
> Is that possible to invert the horizontal direction (from "left to right" to "right to left")?

The plugin doesn't provide any way to do it. 
But you can always create your own arrow elements and assign to them the methods `moveTo` or `moveSlideRight` or `moveSlideLeft` as you please. So yeah, in that way it is possible.

[Demo online](http://jsfiddle.net/97tbk/1296/)

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    controlArrows:false
});

$('#arrow-left').click(function(){
	$.fn.fullpage.moveSlideLeft();
});

$('#arrow-right').click(function(){
	$.fn.fullpage.moveSlideRight();
});
```
