### ISSUE TITLE
How to Link to a particular section inside pagepiling from another page.

### ISSUE THREAD

**Issue by sanjay17kol** [alvarotrigo/pagePiling.js#97]
How to Link to a particular section inside pagepiling from another page 
I have a common menu when user navigate to different page using that menu , on clicking the contact tab , i want to display the contact section inside pagepiling rather than a different page.

**Comment by alvarotrigo** [comment]
Just use the URL with the anchor link, for example:
http://alvarotrigo.com/pagePiling/#page2

Notice the `#page2` at the end, which is the anchor name for the 2nd section.

**Comment by sanjay17kol** [comment]
Its happening on the same page but its not working when i come from different page.
Its just showing the top section , the landing section , not navigating to that particular section

**Comment by alvarotrigo** [comment]
It works on the link i gave you.

**Comment by sanjay17kol** [comment]
It navigates to the the page but not to that section

**Comment by alvarotrigo** [comment]
Again, It works on the link i gave you.

**Comment by sanjay17kol** [comment]
Hi,
I got the solution actually I was initializing pagepiling after window load function of jquery
 , instead it should be initialized within document ready function of jquery
